### ISSUE TITLE
High/erroneous reads being received

### ISSUE THREAD

**Issue by DJBenson** [pavoni/pyloopenergy#19]
I've integrated pyloopenergy with Domoticz to provide realtime gas and electricity consumption to my home automation platform but at the moment it is plagued with reads which are off the scale in terms of what I would expect, at least one read per hour from the electricity feed and one every couple of hours from the gas feed.

The values are unique in their appearance - they all have the value 18 446 744 073 709 552 000 Wh

My integration simply takes your sample script (with both gas and electricity enabled) which I've added a line to call the Domoticz web service using Python (I simply pass the value from your script to the Domoticz URL on my network and Domoticz registers that read).

Do you have any idea what this strangely random value might be that the service is returning?

**Comment by pavoni** [comment]
Don't think I've seen that. Sounds like you're a developer - if so can you add a trace to the electicity callback? Something like:-
```python
    def _update_elec(self, arg):
        self.connected_ok = True
        self.updated_in_interval = True
        self.elec_kw = arg['inst']/1000.0
        LOG.error('Electricity trace: %s', arg)
        LOG.info('Electricity rate: %s', self.elec_kw)
        if self._elec_callback is not None:
            self._elec_callback()
```

This will trace the raw data that is sent from loop, looking something like:-
````
RROR:pyloopenergy.loop_energy:Electricity trace: {'deviceTimestamp': 1472825264, 'rssi': -70, 'serial': '27f1', 'inst': 2476, 'lqi': 46}
````

That should allow us to try to work out what is odd about the packets that give the odd readings.

If you're not a developer I can send you another branch to run...

**Comment by pavoni** [comment]
You also need to turn on tracing, modify the demo code at the top to include the logging details - something like
```python
import pyloopenergy

import time

import logging

logging.basicConfig(level=logging.DEBUG)
# logging.basicConfig(level=logging.INFO)
LOG = logging.getLogger(__name__)

def gas_trace():
    print("Gas =", le.gas_useage)

def elec_trace():
    print("Electricity =", le.electricity_useage)
```

**Comment by DJBenson** [comment]
Nope I'm not a developer but I'm a fairly competent tinkerer

Here's my modified script which I use to feed the reads to Domoticz;

`#!/usr/bin/python3
import pyloopenergy
import time
import urllib

def gas_trace():
    print("Gas =", le.gas_useage)
    f = "http://127.0.0.1/json.htm?type=command&param=udevice&idx=54&svalue=%s" % int(le.gas_useage*1000)
    urllib.request.urlopen(f).read

def elec_trace():
    print("Electricity =", le.electricity_useage)
    f = "http://127.0.0.1/json.htm?type=command&param=udevice&idx=53&svalue=%s" % int(le.electricity_useage*1000)
    urllib.request.urlopen(f).read

elec_serial = 'REMOVED';
elec_secret = 'REMOVED';

gas_serial = 'REMOVED';
gas_secret = 'REMOVED';

le = pyloopenergy.LoopEnergy(elec_serial, elec_secret, gas_serial, gas_secret, pyloopenergy.IMPERIAL, 39.1)
le.subscribe_gas(gas_trace)
le.subscribe_elecricity(elec_trace)`

The multiplication by 1000 in my code is to ensure Domoticz is fed with KWH instead of WH returned by the script (even if I misunderstood the script returning WH my readings were out by a factor of 1000 without this modification so I think I'm right)

**Comment by DJBenson** [comment]
So I've got logging working in my script - am I looking for those large values now?

**Comment by pavoni** [comment]
Perfect - post them when you see a bad reading!

**Comment by pavoni** [comment]
(Are you tracing the raw data (ie did you add my LOG.error line)? That will give us the best data.

**Comment by DJBenson** [comment]
Think so - I'll edit the script above to show what's currently running...

**Comment by DJBenson** [comment]
Sorry about the formatting, for some reason I can't get it to wrap my code in code tags :(

**Comment by pavoni** [comment]
How do the logs look?

**Comment by DJBenson** [comment]
I was about to say "crazy" but then realised my wife has put the tumble dryer on!!

I'll leave it debugging to a text file for an hour or so and then check back for the value(s). Looking in Domoticz it's a bit sporadic but in some instances it occurs several times per hour.

Cheers for the help so far, when I have anything meaningful I'll jump back on here.

**Comment by pavoni** [comment]
I've just pushed a version with the traces added. You can pull this with
````
git checkout add_traces
````
This will make sure you're getting the full raw data. Be a shame to wait an hour for a bad reading - and not get the raw data.

Of course if you've changed the code your self your traces should already include lines starting with ERROR like:-
````
ERROR:pyloopenergy.loop_energy:Electricity trace: {'inst': 295, 'serial': '27f1', 'lqi': 44, 'deviceTimestamp': 1472826937, 'rssi': -70}
````

The normal traces without the ERROR line may not give us what we need.

**Comment by DJBenson** [comment]
Erm...nope - here's a sample of what's coming down...

`DEBUG:socketIO_client.transports:[wss://www.your-loop.com:443/socket.io/1/websocket/<REMOVED>] [packet sent] 2:::
DEBUG:socketIO_client.transports:[wss://www.your-loop.com:443/socket.io/1/websocket/<REMOVED>] [packet received] 5:::{"name":"electric_realtime","args":[{"lqi":44,"rssi":-57,"deviceTimestamp":1472827100,"inst":3076,"serial":"<REMOVED>"}]}
INFO:pyloopenergy.loop_energy:Electricity rate: 3.076
Electricity = 3.076
DEBUG:pyloopenergy.loop_energy:LoopEnergy thread poll
DEBUG:socketIO_client.transports:[wss://www.your-loop.com:443/socket.io/1/websocket/<REMOVED>] [packet received] 5:::{"name":"electric_realtime","args":[{"lqi":45,"rssi":-57,"deviceTimestamp":1472827111,"inst":3079,"serial":"<REMOVED>"}]}
INFO:pyloopenergy.loop_energy:Electricity rate: 3.079
Electricity = 3.079
DEBUG:socketIO_client.transports:[wss://www.your-loop.com:443/socket.io/1/websocket/<REMOVED>] [packet received] 2::
DEBUG:socketIO_client.transports:[wss://www.your-loop.com:443/socket.io/1/websocket/<REMOVED>] [packet received] 5:::{"name":"electric_realtime","args":[{"lqi":44,"rssi":-57,"deviceTimestamp":1472827122,"inst":3057,"serial":"<REMOVED>"}]}
INFO:pyloopenergy.loop_energy:Electricity rate: 3.057
Electricity = 3.057
DEBUG:socketIO_client.transports:[wss://www.your-loop.com:443/socket.io/1/websocket/<REMOVED>] [packet sent] 2:::
DEBUG:pyloopenergy.loop_energy:LoopEnergy thread poll
DEBUG:socketIO_client.transports:[wss://www.your-loop.com:443/socket.io/1/websocket/<REMOVED>] [packet received] 5:::{"name":"electric_realtime","args":[{"lqi":43,"rssi":-57,"deviceTimestamp":1472827133,"inst":3079,"serial":"<REMOVED>"}]}
INFO:pyloopenergy.loop_energy:Electricity rate: 3.079
Electricity = 3.079`

I think the websocket had some sensitive data in so I removed that along with my serial.

**Comment by pavoni** [comment]
That should be good enough. Let's wait for a suitable error!

**Comment by DJBenson** [comment]
Does it make a difference that I added the logging code to my script (which is your sample script) rather than the loop_energy.py script?

**Comment by DJBenson** [comment]
The debug has been running for 24 hours now and although Domoticz is still showing regular occurrences of this value, there is nothing untoward in the debug data.

[Anonymised ERROR log](http://paste.ubuntu.com/23128387/)
[Anonymised INFO log](http://paste.ubuntu.com/23128393/)
[Anonymised DEBUG log](http://paste.ubuntu.com/23128409/)

So the error appears to be occurring between the output from your script (which seems to be returning nothing but valid results), my script (which just adds the connection to Domoticz) and Domoticz itself :(

**Comment by pavoni** [comment]
Probably won't help - but you might want to change your script to use the python `requests` library like this one https://www.domoticz.com/wiki/Wemo. That's the library that I've seen most python libraries use. Worth asking on the Domoticz forums too if you haven't already - looks like there are other pyon integrators there. Good luck...
